#! /bin/bash

# shellcheck disable=SC2164
cd ../workflow/output;

# STAR mapping
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C1_1_S06_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C1_1_S06_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C1_1_S06_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C1_3_S21_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C1_3_S21_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C1_3_S21_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C1_4_S28_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C1_4_S28_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C1_4_S28_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C4_1_S07_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C4_1_S07_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C4_1_S07_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C4_4_S29_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C4_4_S29_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C4_4_S29_merged_R2.fastq &
wait $!
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C5_1_S08_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C5_1_S08_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C5_1_S08_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C5_2_S14_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C5_2_S14_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C5_2_S14_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_C5_3_S22_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C5_3_S22_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_C5_3_S22_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_Ctrl_1_S05_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Ctrl_1_S05_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Ctrl_1_S05_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_Ctrl_3_S20_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Ctrl_3_S20_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Ctrl_3_S20_merged_R2.fastq &
wait $!
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_Ctrl_4_S27_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Ctrl_4_S27_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Ctrl_4_S27_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_Nas2_2_S13_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Nas2_2_S13_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Nas2_2_S13_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_Nas2_3_S19_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Nas2_3_S19_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Nas2_3_S19_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/half_Nas2_4_S26_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Nas2_4_S26_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/half_Nas2_4_S26_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/U_Undetermined_X_S00_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/U_Undetermined_X_S00_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/U_Undetermined_X_S00_merged_R2.fastq &
wait $!
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C1_1_S02_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C1_1_S02_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C1_1_S02_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C1_3_S16_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C1_3_S16_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C1_3_S16_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C1_4_S25_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C1_4_S25_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C1_4_S25_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C4_1_S03_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C4_1_S03_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C4_1_S03_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C4_2_S11_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C4_2_S11_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C4_2_S11_merged_R2.fastq &
wait $!
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C4_3_S17_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C4_3_S17_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C4_3_S17_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C5_1_S04_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C5_1_S04_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C5_1_S04_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C5_2_S12_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C5_2_S12_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C5_2_S12_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_C5_3_S18_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C5_3_S18_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_C5_3_S18_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_Ctrl_2_S10_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Ctrl_2_S10_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Ctrl_2_S10_merged_R2.fastq &
wait $!
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_Ctrl_3_S15_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Ctrl_3_S15_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Ctrl_3_S15_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_Ctrl_4_S24_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Ctrl_4_S24_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Ctrl_4_S24_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_Nas2_1_S01_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Nas2_1_S01_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Nas2_1_S01_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_Nas2_2_S09_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Nas2_2_S09_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Nas2_2_S09_merged_R2.fastq &
STAR --genomeDir /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/4_aligned_sequences/star_index --runThreadN 4 --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --outFileNamePrefix AFAC/wo_Nas2_4_S23_ --readFilesIn /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Nas2_4_S23_merged_R1.fastq /tempor/kchennen/RAinRARE_RNAseqPipe/workflow/output/3_merged_lanes/wo_Nas2_4_S23_merged_R2.fastq &
